name: Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install JDK for build
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get npm cache directory
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"
    - name: Cache Node.js modules
      uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - run: npm ci
    - name: Install JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
        java-package: jre
    - name: Run headless test for Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install xvfb
        sudo apt-get autoremove
        xvfb-run --auto-servernum npm test
    - name: Run headless test for non-Linux
      if: runner.os != 'Linux'
      run: npm test
